server:
  servlet:
#    context-path: /api
     context-path: /
---
spring:
  profiles: development
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost/${DB_NAME}?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#security:
#  oauth2:
#    client:
#      client-id: fooClientIdPassword
#      client-secret: secret
#      access-token-uri: http://localhost:${SERVER_PORT}/oauth/token
#    resource:
#      user-info-uri: http://localhost:${SERVER_PORT}/api/v1/users/me
github:
  client:
    clientId: 23f8ccedc9dc812052b3
    clientSecret: 6fcf6d606007da8fc3b8a58f4623d9e67c1bab59
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
server:
  port: ${SERVER_PORT}
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
server:
  port: ${SERVER_PORT}